"""clean initial schema

Revision ID: f911524e5267
Revises: 001
Create Date: 2025-09-13 21:10:21.457180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f911524e5267'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'queue_auditus', ['spotify_id'])
    op.create_unique_constraint(None, 'queue_jukemir', ['spotify_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queue_jukemir', type_='unique')
    op.drop_constraint(None, 'queue_auditus', type_='unique')
    op.alter_column('metrics', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
