services:
  postgres:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    container_name: postgres-db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/db/data
      # - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  collecter:
    build:
      context: ..
      dockerfile: docker/collecter/Dockerfile
    container_name: python-collecter
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local  # Persistent
