services:
  postgres:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test 
      POSTGRES_DB: vectordb
      # Optional: Customize PostgreSQL config
      # POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/db/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  embedder:
    build:
      context: ..
      dockerfile: docker/collection/Dockerfile
    container_name: song-collector
    environment:
      DB_USER: postgres
      DB_PASSWORD: test
      SPOTIFY_ID: "a766651ba4b744ed82f1e520a75b2455"
      SPOTIFY_SECRET: "767732da0b064b838ebe5d0e3f6ce4eb"
      LD_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:/lib"

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: vectordb
      # Set this to "1" to enable development mode
      DEVELOPMENT_MODE: "1"
    # volumes:
    #   - ./app:/app
    depends_on:
      postgres:
        condition: service_healthy
    # Alternative development command that uses uv directly
    # Uncomment for development mode with hot reloading
    # command: sh -c "uv pip install --system -e . && python main.py"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local  # Persistent
